INSERT INTO subject (signature, name, ects) VALUES ('110620', 'Filozofia', 3)
INSERT INTO subject (signature, name, ects) VALUES ('120110', 'Badania marketingowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('120151', 'Mathematical Economics', 3)
INSERT INTO subject (signature, name, ects) VALUES ('120480', 'Prawo międzynarodowe publiczne', 3)
INSERT INTO subject (signature, name, ects) VALUES ('120490', 'Prawo pracy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('120700', 'Zarządzanie projektami', 3)
INSERT INTO subject (signature, name, ects) VALUES ('120920', 'Marketing międzynarodowy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('120921', 'International Marketing', 3)
INSERT INTO subject (signature, name, ects) VALUES ('121040', 'Biznesplan', 3)
INSERT INTO subject (signature, name, ects) VALUES ('121110', 'Fundusze strukturalne Unii Europejskiej', 3)
INSERT INTO subject (signature, name, ects) VALUES ('121390', 'Zarządzanie projektami Unii Europejskiej', 3)
INSERT INTO subject (signature, name, ects) VALUES ('121401', 'Management in International Business', 3)
INSERT INTO subject (signature, name, ects) VALUES ('121500', 'Rynek kapitałowy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('130660', 'Prawo podatkowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('210100', 'Historia myśli ekonomicznej', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('210110', 'Prawo gospodarcze', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('210130', 'Ekonomia', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220281', 'International Marketing', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220340', 'Mikroekonometria', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220341', 'Microeconometrics', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220380', 'Polityka pieniężna', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220430', 'Portfel inwestycyjny', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('220431', 'Investment portfolio', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220440', 'Postępowanie nabywców na rynku', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220441', 'Customer Behavior', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220500', 'Przedsiębiorczość', 1.5)
INSERT INTO subject (signature, name, ects) VALUES ('220501', 'Entrepreneurship', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220530', 'Rachunkowość zarządcza', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220570', 'Statystyczne metody wielowymiarowej analizy ', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220580', 'Statystyka matematyczna I', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220590', 'Statystyka społeczna', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220620', 'Sztuczna inteligencja', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220629', 'Sztuczna inteligencja (e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220680', 'Ubezpieczenia społeczne', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220740', 'Zaawansowana rachunkowość finansowa', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('220741', 'Advanced Financial Accounting', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220750', 'Zarządzanie bankiem', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('220751', 'Bank management', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('220755', 'Zarządzanie bankiem (blended learning)', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('220770', 'Zarządzanie logistyczne', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220771', 'Logistics Management', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220820', 'Zarządzanie wartością przedsiębiorstwa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('220960', 'Postępowanie sądowo-administracyjne', 3)
INSERT INTO subject (signature, name, ects) VALUES ('221320', 'Logistyka międzynarodowa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('221321', 'International Logistics', 3)
INSERT INTO subject (signature, name, ects) VALUES ('221330', 'Międzynarodowe finanse przedsiębiorstw', 3)
INSERT INTO subject (signature, name, ects) VALUES ('221331', 'International Corporate Finance', 3)
INSERT INTO subject (signature, name, ects) VALUES ('221340', 'Globalizacja i regionalizacja w stosunkach międzyn', 3)
INSERT INTO subject (signature, name, ects) VALUES ('221370', 'Kulturowe uwarunkowania biznesu międzynarodowego', 3)
INSERT INTO subject (signature, name, ects) VALUES ('221470', 'Zarządzanie operacyjne', 3)
INSERT INTO subject (signature, name, ects) VALUES ('221471', 'Operations Management', 3)
INSERT INTO subject (signature, name, ects) VALUES ('221480', 'Metody statystyczne II', 3)
INSERT INTO subject (signature, name, ects) VALUES ('221481', 'Statistical Methods II (QEM)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('221640', 'Technologiczne uwarunkowania biznesu międzynarodoweg', 3)
INSERT INTO subject (signature, name, ects) VALUES ('221650', 'Instytucjonalne uwarunkowania biznesu międzynarodowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222000', 'Algebra i analiza matematyczna', 6)
INSERT INTO subject (signature, name, ects) VALUES ('222040', 'Ekonometria finansowa I', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222041', 'Financial Econometrics I', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222050', 'Ekonometria stosowana', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222060', 'Ekonometria szeregów czasowych', 6)
INSERT INTO subject (signature, name, ects) VALUES ('222070', 'Ekonomia emerytalna', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222080', 'Ekonomia instytucjonalna', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('222090', 'Ekonomia menedżerska', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('222091', 'Managerial Economics', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222100', 'Ekonomia międzynarodowa (zaawansowana)', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('222110', 'Ekonomia pracy', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('222120', 'Ekonomia rozwoju', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('222130', 'Ekonomia sektora publicznego', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('222140', 'Ekonomia środowiska', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('222150', 'Ekonomia matematyczna i dynamiczna optymalizacja', 6)
INSERT INTO subject (signature, name, ects) VALUES ('222151', 'Mathematical economics and optimal control theory', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222160', 'Etyka w biznesie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222230', 'Informacyjne systemy zarządzania', 6)
INSERT INTO subject (signature, name, ects) VALUES ('222250', 'Inżynieria finansowa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222260', 'Inżynieria oprogramowania', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222290', 'Makroekonomia (zaawansowana)', 6)
INSERT INTO subject (signature, name, ects) VALUES ('222291', 'Advanced Macroeconomics', 6)
INSERT INTO subject (signature, name, ects) VALUES ('222300', 'Marketing terytorialny', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222321', 'Introduction to Probability Theory and Stochastic Pr', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222340', 'Międzynarodowe rynki finansowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222370', 'Mikroekonomia (zaawansowana)', 6)
INSERT INTO subject (signature, name, ects) VALUES ('222371', 'Advanced Microeconomics (QEM)', 6)
INSERT INTO subject (signature, name, ects) VALUES ('222380', 'Państwo a biznes', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222410', 'Polityka gospodarcza', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222451', 'Poland in the European Union', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222460', 'Prawo finansowe i podatkowe', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('222461', 'Financial and Tax Law', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222470', 'Prawo handlowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222490', 'Rachunek kosztów', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222491', 'Cost Accounting (ACCA)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222580', 'Rachunek prawdopodobieństwa i procesy stochastyczn', 6)
INSERT INTO subject (signature, name, ects) VALUES ('222600', 'Zarządzanie kapitałem ludzkim', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222610', 'Zarządzanie procesami', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222620', 'Zarządzanie strategiczne', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222621', 'Strategic Management', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222660', 'Zewnętrzne stosunki ekonomiczne Unii Europejskiej', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222670', 'Ekonomiczna analiza prawa czynów niedozwolonych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222700', 'Podstawy ekonomicznej analizy prawa I', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222710', 'Podstawy ekonomicznej analizy prawa II', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222730', 'Ekonomiczna analiza prawa publicznego', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222800', 'Nieklasyczne metody optymalizacj', 6)
INSERT INTO subject (signature, name, ects) VALUES ('222810', 'Rachunkowość zarządcza i rachunek kosztów', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222811', 'Management and Cost Accounting', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222940', 'Teoria gier', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222950', 'Ekonometria przestrzenna', 6)
INSERT INTO subject (signature, name, ects) VALUES ('222970', 'Teoria zarządzania', 3)
INSERT INTO subject (signature, name, ects) VALUES ('222980', 'Prawo cywilne', 1.5)
INSERT INTO subject (signature, name, ects) VALUES ('222990', 'Ekonometria panelowa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223010', 'Analiza matematyczna II', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223011', 'Mathematical Analysis II (QEM)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223031', 'Industrial Economics (QEM)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223050', 'Makroekonomia zaawansowana I', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('223060', 'Budowa i eksploatacja baz danych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223090', 'Big data', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223100', 'Prezentacja i wizualizacja danych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223110', 'Podstawowe i zaawansowane programowanie oraz statyst', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223120', 'Data Mining', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223190', 'Metody ilościowe i jakościowe w naukach ekonomicznyc', 7.5)
INSERT INTO subject (signature, name, ects) VALUES ('223200', 'Dyplomacja gospodarcza', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223230', 'Ekonomia innowacji i zarządzanie innowacjami', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('223240', 'Środowisko naturalne i energia: konflikty i współpra', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223241', 'Natural Environment and Energy: International Confl', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223250', 'Ekonomia Behawioralna w e-biznesie', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('223260', 'Ekonomia niedoskonałej konkurencji', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('223270', 'Technologie cyfrowe w relacjach gospodarczych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223280', 'Finansowanie i wycena spółek technologicznych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223281', 'Financing and Valuation of High-Tech Companies', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223290', 'Strategie i modele e-biznesu', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223300', 'Podstawy analizy danych w e-biznesie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223310', 'Analiza i zastosowania sieci społecznych w interne', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223320', 'Globalne ubóstwo, niedorozwój i rozwój', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223330', 'Regiony turystyczne', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('223350', 'Prawo e-biznesu', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223370', 'Nowe technologie w marketingu', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223389', 'Podstawy przedsiębiorczości tech.(e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223390', 'Strategiczne zarządzanie projektami', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223420', 'Marketing usług turystycznych i rekreacyjnych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223421', 'Marketing of Tourism and Recreational Services', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223450', 'Statystyczne metody analizy ubóstwa, wykluczenia spo', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223470', 'Analiza historii zdarzeń z wykorzystaniem narzędzi', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223480', 'Regresja logistyczna z wykorzystaniem narzędzi SAS', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223490', 'Statystyczne reguły decyzyjne', 6)
INSERT INTO subject (signature, name, ects) VALUES ('223500', 'Zarządzanie finansami na rynku międzynarodowym', 3)
INSERT INTO subject (signature, name, ects) VALUES ('223960', 'Podstawy zarządzania projektami', 3)
INSERT INTO subject (signature, name, ects) VALUES ('224380', 'Efektywne zarządzanie IT w przedsiębiorstwie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('224390', 'Obliczenia i przetwarzanie danych w chmurze-cloud co', 3)
INSERT INTO subject (signature, name, ects) VALUES ('224409', 'Zarządzanie przedsiębiorstwem tur. (e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('224410', 'Style życia a usługi czasu wolnego', 1.5)
INSERT INTO subject (signature, name, ects) VALUES ('224520', 'Finanse i rachunkowość menedżerska', 7.5)
INSERT INTO subject (signature, name, ects) VALUES ('224550', 'Logistyka', 3)
INSERT INTO subject (signature, name, ects) VALUES ('224560', 'Prawne uwarunkwania pracy menedżera', 3)
INSERT INTO subject (signature, name, ects) VALUES ('224570', 'Przedsiębiorczość i etyka działalności zawodowej i p', 3)
INSERT INTO subject (signature, name, ects) VALUES ('224590', 'Trening pracy zespołowej i wykorzystania narzędzi me', 3)
INSERT INTO subject (signature, name, ects) VALUES ('225020', 'Wprowadzenie do zarządzania projektami', 3)
INSERT INTO subject (signature, name, ects) VALUES ('225050', 'Rachunkowość projektów', 3)
INSERT INTO subject (signature, name, ects) VALUES ('225060', 'Podstawy organizacji i zarządzania', 3)
INSERT INTO subject (signature, name, ects) VALUES ('225090', 'Kierowanie ludżmi w projektach', 3)
INSERT INTO subject (signature, name, ects) VALUES ('225110', 'Zarządzanie przedsiębiorstwem', 3)
INSERT INTO subject (signature, name, ects) VALUES ('225130', 'Zarzadzanie procesami biznesowymi', 3)
INSERT INTO subject (signature, name, ects) VALUES ('225540', 'Kreowanie wartości klienta', 3)
INSERT INTO subject (signature, name, ects) VALUES ('226020', 'Analiza efektywności projektów', 6)
INSERT INTO subject (signature, name, ects) VALUES ('226030', 'Controling i audyt finansowy przedsiębiorstwa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('226040', 'Diagnostyka finansowa przedsiębiorstwa', 6)
INSERT INTO subject (signature, name, ects) VALUES ('226060', 'Finanse korporacji', 3)
INSERT INTO subject (signature, name, ects) VALUES ('226070', 'Tradycyjne i alternatywne źródła finansowania przedi', 3)
INSERT INTO subject (signature, name, ects) VALUES ('226080', 'Rachunkowość finansowa i menedżerska', 6)
INSERT INTO subject (signature, name, ects) VALUES ('226100', 'Zastosowania inżynierii finansowej', 6)
INSERT INTO subject (signature, name, ects) VALUES ('226110', 'Zintegrowane zarządzanie ryzykiem - ERM', 3)
INSERT INTO subject (signature, name, ects) VALUES ('226140', 'Badania empiryczne w naukach prawniczych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('226150', 'Przedsiębiorczość - perspektywa startupu', 3)
INSERT INTO subject (signature, name, ects) VALUES ('226151', 'Startup entrepreneurship', 3)
INSERT INTO subject (signature, name, ects) VALUES ('226160', 'Zaawansowana analityka biznesowa - siła modeli pred', 6)
INSERT INTO subject (signature, name, ects) VALUES ('229050', 'Zarządzanie strategiczne przedsiebiorstwem', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230060', 'Analiza techniczna i fundamentalna', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('230080', 'Badanie sprawozdań finansowych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230120', 'Komunikacja społeczna', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230200', 'Ekonometria bayesowska', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230240', 'Ekonometryczne modele nieliniowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230300', 'Europejski system transportowy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230460', 'Kierowanie zespołem projektowym', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230481', 'Intercultural Communication', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230510', 'Logistyka dystrybucji', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230538', 'Financial Frauds (e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230540', 'Marketing na rynku instytucjonalnym', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230541', 'Business-to-Business Marketing', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230570', 'Marketing usług transportowych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230710', 'Międzynarodowe rynki transportowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230720', 'Modele i prognozy demograficzne', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230770', 'Multimedialne technologie informacyjne', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230809', 'Nowoczesne systemy dystrybucji w przemyśle (e-learni', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230820', 'Organizacja projektowa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230880', 'Podstawy informacyjne marketingu', 3)
INSERT INTO subject (signature, name, ects) VALUES ('230910', 'Polityka budżetowa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231090', 'Proces motywowania pracowników', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231110', 'Programowanie dynamiczne i modele rekrutacyj.w eko.', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231150', 'Rachunkowość w banku', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231170', 'Reasekuracja', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231210', 'Restrukturyzacja przedsiębiorstwa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231220', 'Rozwój aplikacji biznesowych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231230', 'Rynek instrumentów pochodnych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231231', 'Derivatives Market', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231380', 'Strategia personalna przedsiębiorstwa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231420', 'Strategie konkurencji i rozwoju polskich przedsięb', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231430', 'Strategie marketingowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231431', 'Marketing Strategies', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231450', 'Systemy baz danych II', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231480', 'Planowanie biznesu', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231510', 'Prawne uwarunkowania prowadzenia własnego biznesu', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231560', 'Teoria opodatkowania', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231571', 'Theory of Economic Growth', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231670', 'Konwersatorium z ekonomii', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231760', 'Marketing dóbr luksusowych i o charakterze symbolic', 3)
INSERT INTO subject (signature, name, ects) VALUES ('231880', 'Alternatywny pieniądz', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232000', 'Międzynarodowe strategie kooperacji przedsiębiorst', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232080', 'Techniki aktuarialne w praktyce ubezpieczeń na życie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232121', 'Competitiveness of Regions', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232129', 'Konkurencyjność regionów (e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232160', 'Postępowanie podatkowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232251', 'International Management', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232279', 'Nadzór korporacyjny (e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232301', 'Business Strategies for Central and Eastern Europe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232461', 'National Innovation Systems in the World Economy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232580', 'Teoria i polityka kursów walutowych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232600', 'Analiza strategiczna przedsiębiorstwa w wymiarze m', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232650', 'Fuzje i przejęcia przedsiębiorstw', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232651', 'Mergers and Acquisitions of Enterprises', 3)
INSERT INTO subject (signature, name, ects) VALUES ('232770', 'Partnerstwo publiczno-prywatne', 1.5)
INSERT INTO subject (signature, name, ects) VALUES ('232901', 'Strategic Analysis of European Markets', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233010', 'Analiza koniunktury i badanie rynków zagranicznych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233030', 'Analiza wzorów konsumpcji gospodarstw domowych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233040', 'Analizy rynku metodami ilościowymi', 6)
INSERT INTO subject (signature, name, ects) VALUES ('233060', 'Budżet samorządowy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233070', 'Business Intelligence', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233160', 'e-Gospodarka i otoczenie społeczno-prawne', 6)
INSERT INTO subject (signature, name, ects) VALUES ('233180', 'Ekonometria finansowa II', 6)
INSERT INTO subject (signature, name, ects) VALUES ('233200', 'Ekonomia polityczna', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233240', 'Euromarketing', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233291', 'Innovation in Regional and Local Economy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233310', 'Jakościowe badania marketingowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233350', 'Kryzysy finansowe i stabilność finansowa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233370', 'Laboratorium z rachunkowości zarządczej', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233450', 'Międzynarodowe standardy sprawozdawczości', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233461', 'General Equilibrium Frameworks', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233490', 'Optymalizacja podatkowa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233510', 'Plan zarządzania nieruchomością', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233580', 'Prawo celne', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233590', 'Prawo karne skarbowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233640', 'Problemy demograficzne świata', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233680', 'Przygotowanie projektów finansowanych ze środków U', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233710', 'Regulacje i nadzór nad rynkami finansowymi', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233850', 'Statystyka aktuarialna i teoria ryzyka', 6)
INSERT INTO subject (signature, name, ects) VALUES ('233880', 'Strategie informatyzacji gospodarki', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233890', 'Strategie kooperacji przedsiębiorstw', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233900', 'Strategie wejścia polskich firm na rynki wschodnie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233910', 'Struktura kapitału w przedsiębiorstwie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233960', 'Techniczne aspekty zarządzania nieruchomościami', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233970', 'Teoria ryzyka', 3)
INSERT INTO subject (signature, name, ects) VALUES ('233990', 'VAT w działalności gospodarczej', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234000', 'Wartościowanie i ocena pracy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234040', 'Zaawansowana bankowość inwestycyjna', 6)
INSERT INTO subject (signature, name, ects) VALUES ('234041', 'Advanced Investment Banking', 6)
INSERT INTO subject (signature, name, ects) VALUES ('234060', 'Zaawansowane modelowanie symulacyjne', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234080', 'Zarządzanie innowacjami w przedsiębiorstwie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234100', 'Zarządzanie portfelem kredytowym banku', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234110', 'Zarządzanie projektami informatycznymi', 6)
INSERT INTO subject (signature, name, ects) VALUES ('234139', 'Zarządzanie przedsięwzięciami inwestycyjnymi(e-lea', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234140', 'Zarządzanie ryzykiem finansowym w przedsiębiorstwi', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234141', 'Corporate Financial Risk Management', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234150', 'Zarządzanie ryzykiem rynkowym i operacyjnym', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234301', 'Negotiations', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234480', 'Zewnętrzny i wewnętrzny audyt i kontrola (ACCA-P)', 6)
INSERT INTO subject (signature, name, ects) VALUES ('234490', 'Zarządzanie finansami (ACCA-P)', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('234630', 'Rachunkowość w jednostkach sfery budżetowej', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234650', 'Zaawansowane metody teorii gier', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234670', 'Unia Europejska jako podmiot w stosunkach międzyna', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234720', 'Instytucje sektora finansowego', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234750', 'Reasekuracja - aspekty aktuarialne', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234791', 'Managing Research and Development (R&D) in Transnati', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234810', 'Ekonomiczna analiza prawa zawodów regulowanych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234881', 'Monetary Economics', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234900', 'Modelowanie wieloagentowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234910', 'Polskie prawo podatkowe (ACCA-P)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('234920', 'Sprawozdawczość finansowa i rachunkowość grup kapit', 6)
INSERT INTO subject (signature, name, ects) VALUES ('235100', 'Zarządzanie marką na rynku międzynarodowym', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('235101', 'Brand Management on International Market', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235110', 'Międzynarodowe strategie przedsiębiorstw', 6)
INSERT INTO subject (signature, name, ects) VALUES ('235111', 'Firm Strategies in International Business', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235120', 'Organizacje pozarządowe', 1.5)
INSERT INTO subject (signature, name, ects) VALUES ('235140', 'Polityka migracyjna', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235150', 'Porównania systemów gospodarczych-odmiany kapitalizm', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235160', 'Usługi w gospodarce światowej', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235200', 'Finanse behawioralne w praktyce', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235201', 'Applied Behavioral Finance', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235220', 'Zarządzanie ryzykiem finansowym i instrumenty pochod', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('235230', 'Zarządzanie usługami na rynku międzynarodowym', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('235250', 'Gospodarka informacyjna', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235260', 'Komunikacja marketingowa na rynku internetowym', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235280', 'Marketing z wykorzystaniem wyszukiwarek internetowy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235300', 'Start-up technologiczny', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('235310', 'Strategie marketingowe w mediach społecznościowych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235311', 'Social Media Marketing Strategies', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235330', 'Trendy konsumenckie a strategie e-biznesu', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235340', 'Zarządzanie łańcuchem dostaw w e-biznesie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235350', 'Zarządzanie strategiczne IT', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235360', 'Zarządzanie usługami IT', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235370', 'Zarządzanie wiedzą', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235380', 'Innowacje finansowe FinTech', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235381', 'FinTech; Technology and Innovation in Financial Serv', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235410', 'Współczesna teoria ekonometrii', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235440', 'Warsztaty sporządzania pism w postępowaniach adminis', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235450', 'Zawód doradcy podatkowego i etyka zawodowa', 1.5)
INSERT INTO subject (signature, name, ects) VALUES ('235460', 'Propedeutyka rachunkowości', 1.5)
INSERT INTO subject (signature, name, ects) VALUES ('235510', 'Polityka energetyczna', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235590', 'Polityka zdrowotna i finansowanie ochrony zdrowia', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235700', 'Strategie funkcjonalne w przedsiębiorstwach', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235730', 'Pomiar efektywności w ochronie zdrowia', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235790', 'Organizacja i finansowanie własnej działalności gosp', 3)
INSERT INTO subject (signature, name, ects) VALUES ('235840', 'Procesy zarządzania - role menedżerskie w organizacj', 1.5)
INSERT INTO subject (signature, name, ects) VALUES ('235920', 'Historia polskiej dyplomacji', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236069', 'Polityki gospodarcze Unii Europejskiej (e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236071', 'European Strategies and International Business CEMS', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236080', 'Cargo lotnicze', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236090', 'Agencje ratingowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236101', 'Management Strategies in the New Economy CEMS', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236121', 'Digital Media Economics (CEMS)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236151', 'Organizational Behavior - Management Skills (CEMS)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236161', 'Strategic Analysis of European Markets (CEMS)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236181', 'Transition in Central and Eastern Europe (CEMS)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236189', 'Nagrody Nobla-najnowsze trendy w ekonomii(e-learning', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236239', 'Konsument na rynku internetowym (e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236249', 'Korporacje trans. a globalne pozys. ... (e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236279', 'Negocjowanie i zawieranie umów z partnerem (e-learni', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236289', 'Nowoczesne metody budowania wizerunku firmy (e-learn', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236309', 'Podejmowanie decyzji z wykorzyst... (e-lear, econet)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236339', 'Przemysły kultury w gospodarce rynkowej (e-learnin', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236379', 'Społeczne funkcje mediów masowych (e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236399', 'Symulacyjna gra decyzyjna TEES-6(e-learning, econe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236409', 'Zarządzanie infrastrukturą informatyczną(e-lear,econ', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236430', 'Zaawansowane metody analizy statystycznej z wykorz', 6)
INSERT INTO subject (signature, name, ects) VALUES ('236480', 'Budowa oprogramowania dla bazy danych. Język PL/SQ', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236521', 'Cross-Cultural Management', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236570', 'Emisja głosu', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236590', 'Franczyza w biznesie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236599', 'Franczyza w biznesie (e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236721', 'Lifestyles and New Product Development', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236730', 'Podstawy modelowania w R', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236760', 'Marketing sportu', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236850', 'Międzynarodowe planowanie podatkowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236860', 'Teoria i projektowanie badań reprezentacyjnych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('236960', 'Podatki pośrednie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237010', 'Projektowanie aplikacji wspomagających procesy biz', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237039', 'Przywództwo w organizacjach-analiza najlep. (e-learn', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237040', 'Psychologia reklamy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237060', 'Sztuka prezentacji - trening', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237100', 'Europejski rynek usług transportu lotniczego', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237210', 'Warsztaty menedżersko-przywódcze', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237220', 'Wielowymiarowa analiza statystyczna z wykorzystani', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237370', 'Zarządzanie sprzedażą', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237410', 'Coaching', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237481', 'Microeconomics of Competitiveness (licenced by..CEMS', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237770', 'Cashflow 101 - gra edukacyjna Roberta Kiyosaki', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237850', 'Leasing', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237910', 'Metody zarządzania płynnością finansową', 3)
INSERT INTO subject (signature, name, ects) VALUES ('237990', 'Podstawy programowania w języku Java', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238010', 'Pakiet statystyczny R - kurs podstawowy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238030', 'Finansowanie małych i średnich przedsiębiorstw w Pol', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238070', 'Podatki bezpośrednie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238159', 'Finansowanie nieruchomości (e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238161', 'Developing a Winning Sales and Marketing Stra (CEMS)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238171', 'Global Supply Chain Management (CEMS)', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('238201', 'Leadership: Managing, People, System and Self (CEMS)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238231', 'Business Process Outsourcing and Offshoring', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238290', 'Fair Trade a rozwój krajów Południa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238310', 'Credit Scoring i makro-programowanie w SAS', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238380', 'Inkubator przedsiębiorczości', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238400', 'Praktyczne inwestowanie w instrumenty futures na pla', 4.5)
INSERT INTO subject (signature, name, ects) VALUES ('238410', 'Realizacja projektu w formule corporate i project fi', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238479', 'Metody badania opinii z wykorzy. statystyki (e-learn', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238481', 'The application of quantitative methods in finance', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238649', 'Obraz człowieka w ekonomii (e-learning)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238690', 'Feminizm - elementarz filozoficzny', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238730', 'Zarządzanie sobą', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238740', 'Zarządzanie finansami w sektorze publicznym', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238791', 'Energy Security Economics', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238830', 'Ekonomia energii i polityka energetyczna', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238850', 'Stosunki międzynarodowe na Bliskim Wschodzie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238860', 'Gospodarka i polityka Stanów Zjednoczonych i Kanady', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238899', 'Przywództwo w organizacjach-analiza... (econet)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238909', 'Równouprawnienie kobiet i mężczyzn w społ. (e-learn', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238910', 'Finanse muzułmańskie', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238940', 'Biznes lotniczy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('238941', 'Airline Business', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239010', 'Nadużycia na rynku finansowym', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239050', 'Zaawansowane programowanie w języku R', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239170', 'Lobbing i grupy interesu w Unii Europejskiej', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239200', 'Kryptografia stosowana', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239210', 'Inwestycje kapitałowe i finansowe', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239230', 'Historia rynków finansowych', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239250', 'Analiza sytuacyjna przedsiębiorstwa', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239320', 'Zarządzanie ryzykiem bankowym (z wykorzystaniem nar', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239370', 'Wieloletnie planowanie i prognozowanie budżetu', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239411', 'History of the Middle-East', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239420', 'Podstawy aproksymacji - od analizy Fouriera do deep', 6)
INSERT INTO subject (signature, name, ects) VALUES ('239439', 'Innowacje na rynku finans. (e-lea', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239470', 'Społeczna odpowiedzialność biznesu (CSR)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239720', 'Ekonomia sportu', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239901', 'China in the Global Economy', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239920', 'Ucieczka przed podatkiem. Formy, prawne ograniczenia', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239931', 'FinTech and Commerce Startups with Mastercard (CEMS)', 3)
INSERT INTO subject (signature, name, ects) VALUES ('239951', 'Development of Digital Economy 4.0', 3)

INSERT INTO lecturer (signature, name) VALUES ('0566', 'Szulczewski Grzegorz')
INSERT INTO lecturer (signature, name) VALUES ('0395', 'Marciniak Beata')
INSERT INTO lecturer (signature, name) VALUES ('1503', 'Trzebiński Wojciech')
INSERT INTO lecturer (signature, name) VALUES ('0273', 'Kruszewski Robert')
INSERT INTO lecturer (signature, name) VALUES ('0389', 'Menkes Jerzy')
INSERT INTO lecturer (signature, name) VALUES ('1227', 'Kociołek-Pęksa Anna')
INSERT INTO lecturer (signature, name) VALUES ('1066', 'Grucza Bartosz')
INSERT INTO lecturer (signature, name) VALUES ('0014', 'Baranowska-Prokop Ewa')
INSERT INTO lecturer (signature, name) VALUES ('0662', 'Zarzycka Anna M.')
INSERT INTO lecturer (signature, name) VALUES ('0301', 'Kowalik Izabela')
INSERT INTO lecturer (signature, name) VALUES ('0350', 'Marecki Krzyszof')
INSERT INTO lecturer (signature, name) VALUES ('0442', 'Pawlak Zbigniew')
INSERT INTO lecturer (signature, name) VALUES ('0470', 'Proczek Magdalena')
INSERT INTO lecturer (signature, name) VALUES ('0325', 'Lewandowska Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('0991', 'Adamska Agata')
INSERT INTO lecturer (signature, name) VALUES ('1888', 'Frydrych Sylwia')
INSERT INTO lecturer (signature, name) VALUES ('0015', 'Bartkowiak Ryszard')
INSERT INTO lecturer (signature, name) VALUES ('0658', 'Wojciechowska Renata')
INSERT INTO lecturer (signature, name) VALUES ('0241', 'Kloc Kazimierz')
INSERT INTO lecturer (signature, name) VALUES ('0544', 'Sulejewicz Aleksander')
INSERT INTO lecturer (signature, name) VALUES ('0583', 'Kightley Marta')
INSERT INTO lecturer (signature, name) VALUES ('1906', 'Korczyk Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('0080', 'Czyżowicz Wiesław')
INSERT INTO lecturer (signature, name) VALUES ('0153', 'Gospodarek Jerzy')
INSERT INTO lecturer (signature, name) VALUES ('0381', 'Morawska Sylwia')
INSERT INTO lecturer (signature, name) VALUES ('0513', 'Siemiątkowski Tomasz')
INSERT INTO lecturer (signature, name) VALUES ('1110', 'Dominowska Joanna')
INSERT INTO lecturer (signature, name) VALUES ('1114', 'Gwardzińska Ewa')
INSERT INTO lecturer (signature, name) VALUES ('1277', 'Boberek Łukasz')
INSERT INTO lecturer (signature, name) VALUES ('1489', 'Godlewska Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('1494', 'Gajewski Dominik')
INSERT INTO lecturer (signature, name) VALUES ('0159', 'Grądalski Feliks')
INSERT INTO lecturer (signature, name) VALUES ('1316', 'Sternal Bartosz')
INSERT INTO lecturer (signature, name) VALUES ('0166', 'Gruszczyński Marek')
INSERT INTO lecturer (signature, name) VALUES ('0450', 'Kulpaka Paweł')
INSERT INTO lecturer (signature, name) VALUES ('0493', 'Rosati Dariusz')
INSERT INTO lecturer (signature, name) VALUES ('0519', 'Sławiński Andrzej')
INSERT INTO lecturer (signature, name) VALUES ('0092', 'Liberadzki Kamil')
INSERT INTO lecturer (signature, name) VALUES ('0972', 'Czapiewski Piotr')
INSERT INTO lecturer (signature, name) VALUES ('1254', 'Bańbuła Piotr')
INSERT INTO lecturer (signature, name) VALUES ('1513', 'Grygiel-Tomaszewska Anna')
INSERT INTO lecturer (signature, name) VALUES ('1156', 'Orzechowski Arkadiusz')
INSERT INTO lecturer (signature, name) VALUES ('0035', 'Bombol Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('0385', 'Mróz Bogdan')
INSERT INTO lecturer (signature, name) VALUES ('1120', 'Legutko-Kobus Paulina')
INSERT INTO lecturer (signature, name) VALUES ('0637', 'Wojtysiak-Kotlarski Marcin')
INSERT INTO lecturer (signature, name) VALUES ('0394', 'Marecki Łukasz')
INSERT INTO lecturer (signature, name) VALUES ('0441', 'Paszula Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('0705', 'Krysik Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('0919', 'Pielaszek Marcin')
INSERT INTO lecturer (signature, name) VALUES ('0438', 'Panek Tomasz')
INSERT INTO lecturer (signature, name) VALUES ('0854', 'Podogrodzka Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('1164', 'Juszczak Dorota')
INSERT INTO lecturer (signature, name) VALUES ('0421', 'Olejniczak Jarosław')
INSERT INTO lecturer (signature, name) VALUES ('0251', 'Cichowicz Ewa')
INSERT INTO lecturer (signature, name) VALUES ('0060', 'Bareja Katarzyna')
INSERT INTO lecturer (signature, name) VALUES ('0606', 'Tłaczała Agnieszka')
INSERT INTO lecturer (signature, name) VALUES ('1064', 'Grabowski Rafał')
INSERT INTO lecturer (signature, name) VALUES ('0195', 'Iwanicz-Drozdowska Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('0660', 'Zaleska Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('1001', 'Bieć Alfred')
INSERT INTO lecturer (signature, name) VALUES ('0040', 'Brdulak Halina')
INSERT INTO lecturer (signature, name) VALUES ('0498', 'Rutkowski Krzysztof')
INSERT INTO lecturer (signature, name) VALUES ('0072', 'Cichosz Marzenna')
INSERT INTO lecturer (signature, name) VALUES ('0731', 'Masiukiewicz Piotr')
INSERT INTO lecturer (signature, name) VALUES ('1013', 'Mikołajek-Gocejna Magdalena')
INSERT INTO lecturer (signature, name) VALUES ('1595', 'Strojny Mariusz')
INSERT INTO lecturer (signature, name) VALUES ('0646', 'Werner Aleksander')
INSERT INTO lecturer (signature, name) VALUES ('0312', 'Lesiak Paweł')
INSERT INTO lecturer (signature, name) VALUES ('1229', 'Gębski Łukasz')
INSERT INTO lecturer (signature, name) VALUES ('1427', 'Chmielewska Anna')
INSERT INTO lecturer (signature, name) VALUES ('0398', 'Niedziólka Dorota')
INSERT INTO lecturer (signature, name) VALUES ('0007', 'Aniszewska-Banaś Grażyna')
INSERT INTO lecturer (signature, name) VALUES ('0161', 'Gregorczyk Sylwester')
INSERT INTO lecturer (signature, name) VALUES ('0174', 'Godlewska-Majkowska Hanna')
INSERT INTO lecturer (signature, name) VALUES ('0314', 'Leśniak-Łebkowska Grażyna')
INSERT INTO lecturer (signature, name) VALUES ('0971', 'Bartoszczuk Paweł')
INSERT INTO lecturer (signature, name) VALUES ('1287', 'Zwierzchowski Jan')
INSERT INTO lecturer (signature, name) VALUES ('1274', 'Rynko Maja')
INSERT INTO lecturer (signature, name) VALUES ('0238', 'Kłopotowski Jacek')
INSERT INTO lecturer (signature, name) VALUES ('0548', 'Syczewska Ewa')
INSERT INTO lecturer (signature, name) VALUES ('0291', 'Krysiak Zbigniew')
INSERT INTO lecturer (signature, name) VALUES ('0609', 'Tomczyk Emilia')
INSERT INTO lecturer (signature, name) VALUES ('0610', 'Topolewski Marcin')
INSERT INTO lecturer (signature, name) VALUES ('1286', 'Konopczak Karolina')
INSERT INTO lecturer (signature, name) VALUES ('0621', 'Welfe Aleksander')
INSERT INTO lecturer (signature, name) VALUES ('0154', 'Góra Marek')
INSERT INTO lecturer (signature, name) VALUES ('0012', 'Balcerowicz Leszek')
INSERT INTO lecturer (signature, name) VALUES ('0100', 'Dołęgowski Tomasz')
INSERT INTO lecturer (signature, name) VALUES ('0578', 'Słomka-Gołębiowska Agnieszka')
INSERT INTO lecturer (signature, name) VALUES ('1517', 'Skrzek-Lubasińska Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('0019', 'Bem Dorota')
INSERT INTO lecturer (signature, name) VALUES ('0096', 'Dąbrowski Ireneusz')
INSERT INTO lecturer (signature, name) VALUES ('0402', 'Nojszewska Ewelina')
INSERT INTO lecturer (signature, name) VALUES ('0471', 'Prokop Jacek')
INSERT INTO lecturer (signature, name) VALUES ('0479', 'Próchniak Mariusz')
INSERT INTO lecturer (signature, name) VALUES ('0689', 'Mokrogulski Mateusz')
INSERT INTO lecturer (signature, name) VALUES ('0707', 'Maszczyk Piotr')
INSERT INTO lecturer (signature, name) VALUES ('0676', 'Żukrowska Katarzyna')
INSERT INTO lecturer (signature, name) VALUES ('0988', 'Chmielewiec Beata')
INSERT INTO lecturer (signature, name) VALUES ('1107', 'Wojciechowski Wiktor')
INSERT INTO lecturer (signature, name) VALUES ('1140', 'Ruzik-Sierdzińska Anna')
INSERT INTO lecturer (signature, name) VALUES ('1186', 'Magda Iga')
INSERT INTO lecturer (signature, name) VALUES ('1295', 'Guzikowski Mateusz')
INSERT INTO lecturer (signature, name) VALUES ('1792', 'Gałecka-Burdziak Ewa')
INSERT INTO lecturer (signature, name) VALUES ('0132', 'Falkowski Krzysztof')
INSERT INTO lecturer (signature, name) VALUES ('0206', 'Jarosiński Krzysztof')
INSERT INTO lecturer (signature, name) VALUES ('0309', 'Latoszek Ewa')
INSERT INTO lecturer (signature, name) VALUES ('0136', 'Garbicz Marek')
INSERT INTO lecturer (signature, name) VALUES ('0712', 'Bołkunow Wiktor-')
INSERT INTO lecturer (signature, name) VALUES ('0119', 'Dzierżek Lidia')
INSERT INTO lecturer (signature, name) VALUES ('1097', 'Ciżkowicz Piotr')
INSERT INTO lecturer (signature, name) VALUES ('1581', 'Sadowy Katarzyna')
INSERT INTO lecturer (signature, name) VALUES ('0257', 'Korporowicz Violetta')
INSERT INTO lecturer (signature, name) VALUES ('1358', 'Koloch Grzegorz')
INSERT INTO lecturer (signature, name) VALUES ('0999', 'Growiec Jakub')
INSERT INTO lecturer (signature, name) VALUES ('0218', 'Jastrzębska Ewa Magdalena')
INSERT INTO lecturer (signature, name) VALUES ('0387', 'Myśliwiec Grzegorz')
INSERT INTO lecturer (signature, name) VALUES ('0697', 'Turek Dariusz')
INSERT INTO lecturer (signature, name) VALUES ('1017', 'Klimek Jan')
INSERT INTO lecturer (signature, name) VALUES ('1252', 'Rosiak-Zięba Ewa')
INSERT INTO lecturer (signature, name) VALUES ('0228', 'Kamiński Andrzej')
INSERT INTO lecturer (signature, name) VALUES ('1280', 'Filipkowski Piotr')
INSERT INTO lecturer (signature, name) VALUES ('0998', 'Pruchnicka - Grabias Izabela')
INSERT INTO lecturer (signature, name) VALUES ('0243', 'Kobyliński Andrzej')
INSERT INTO lecturer (signature, name) VALUES ('0342', 'Malinowski Dariusz')
INSERT INTO lecturer (signature, name) VALUES ('1126', 'Kolasa Marcin')
INSERT INTO lecturer (signature, name) VALUES ('0668', 'Ziółkowski Marek')
INSERT INTO lecturer (signature, name) VALUES ('1003', 'Kwas Marek')
INSERT INTO lecturer (signature, name) VALUES ('1152', 'Waszkiewicz Aneta')
INSERT INTO lecturer (signature, name) VALUES ('1248', 'Rojek Miłosz')
INSERT INTO lecturer (signature, name) VALUES ('0089', 'Woźny Łukasz')
INSERT INTO lecturer (signature, name) VALUES ('0006', 'Ambroziak Adam')
INSERT INTO lecturer (signature, name) VALUES ('0628', 'Wierzbicki Jarosław')
INSERT INTO lecturer (signature, name) VALUES ('0410', 'Nowak-Far Artur')
INSERT INTO lecturer (signature, name) VALUES ('0187', 'Hellich Ewa')
INSERT INTO lecturer (signature, name) VALUES ('1330', 'Raulinajtys-Grzybek Monika')
INSERT INTO lecturer (signature, name) VALUES ('0098', 'Dędys Monika')
INSERT INTO lecturer (signature, name) VALUES ('1068', 'Juchniewicz Mateusz')
INSERT INTO lecturer (signature, name) VALUES ('1264', 'Metelski Witalij')
INSERT INTO lecturer (signature, name) VALUES ('0030', 'Błaszczyk Marek')
INSERT INTO lecturer (signature, name) VALUES ('0330', 'Łobejko Stanisław')
INSERT INTO lecturer (signature, name) VALUES ('1002', 'Korpus Joanna')
INSERT INTO lecturer (signature, name) VALUES ('1257', 'Mierzejewska Wioletta')
INSERT INTO lecturer (signature, name) VALUES ('0004', 'Aluchna Maria')
INSERT INTO lecturer (signature, name) VALUES ('0296', 'Krukowska Monika')
INSERT INTO lecturer (signature, name) VALUES ('1266', 'Bełdowski Jarosław')
INSERT INTO lecturer (signature, name) VALUES ('1118', 'Rogowski Wojciech')
INSERT INTO lecturer (signature, name) VALUES ('0649', 'Wieloch Maciej')
INSERT INTO lecturer (signature, name) VALUES ('0968', 'Baran Wioletta')
INSERT INTO lecturer (signature, name) VALUES ('1015', 'Świderska Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('0740', 'Winnicka Justyna')
INSERT INTO lecturer (signature, name) VALUES ('1247', 'Torój Andrzej')
INSERT INTO lecturer (signature, name) VALUES ('0425', 'Ornarowicz Urszula')
INSERT INTO lecturer (signature, name) VALUES ('0647', 'Witkowski Bartosz')
INSERT INTO lecturer (signature, name) VALUES ('0284', 'Knauff Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('0011', 'Adamowicz Elżbieta')
INSERT INTO lecturer (signature, name) VALUES ('0745', 'Żurawski Andrzej')
INSERT INTO lecturer (signature, name) VALUES ('0568', 'Szupiluk Ryszard')
INSERT INTO lecturer (signature, name) VALUES ('1621', 'Rafało Mariusz')
INSERT INTO lecturer (signature, name) VALUES ('1188', 'Kozakiewicz Mariusz')
INSERT INTO lecturer (signature, name) VALUES ('1116', 'Bryk Artur')
INSERT INTO lecturer (signature, name) VALUES ('1234', 'Przanowski Karol')
INSERT INTO lecturer (signature, name) VALUES ('0090', 'Ptak-Chmielewska Aneta')
INSERT INTO lecturer (signature, name) VALUES ('0997', 'Grzenda Wioletta')
INSERT INTO lecturer (signature, name) VALUES ('1577', 'Wąsowicz-Zaborek Elżbieta')
INSERT INTO lecturer (signature, name) VALUES ('1498', 'Napiórkowski Tomasz')
INSERT INTO lecturer (signature, name) VALUES ('1338', 'Nyga-Łukaszewska Honorata -')
INSERT INTO lecturer (signature, name) VALUES ('0622', 'Weresa Marzenna A.')
INSERT INTO lecturer (signature, name) VALUES ('0047', 'Budnikowski Adam')
INSERT INTO lecturer (signature, name) VALUES ('0969', 'Roszkowska Paulina')
INSERT INTO lecturer (signature, name) VALUES ('0120', 'Doligalski Tymoteusz')
INSERT INTO lecturer (signature, name) VALUES ('1160', 'Bernardelli Michał')
INSERT INTO lecturer (signature, name) VALUES ('0465', 'Polańska Krystyna')
INSERT INTO lecturer (signature, name) VALUES ('0116', 'Dziedzic Ewa')
INSERT INTO lecturer (signature, name) VALUES ('1566', 'Jasiński Michał')
INSERT INTO lecturer (signature, name) VALUES ('1624', 'Klepka Michał')
INSERT INTO lecturer (signature, name) VALUES ('0431', 'Opałka Benedykt')
INSERT INTO lecturer (signature, name) VALUES ('1059', 'Bukłaha Emil')
INSERT INTO lecturer (signature, name) VALUES ('0378', 'Molenda Marcin')
INSERT INTO lecturer (signature, name) VALUES ('0131', 'Frątczak Ewa')
INSERT INTO lecturer (signature, name) VALUES ('1596', 'Skwirz Wojciech')
INSERT INTO lecturer (signature, name) VALUES ('1598', 'Rozenbajgier Piotr')
INSERT INTO lecturer (signature, name) VALUES ('1528', 'Iwanicka Aleksandra')
INSERT INTO lecturer (signature, name) VALUES ('0286', 'Kamiński Bogumił')
INSERT INTO lecturer (signature, name) VALUES ('0024', 'Bień Andrzej')
INSERT INTO lecturer (signature, name) VALUES ('2846', 'Zawieska Jakub')
INSERT INTO lecturer (signature, name) VALUES ('0160', 'Orzechowski Remigiusz')
INSERT INTO lecturer (signature, name) VALUES ('0723', 'Szufel Przemysław')
INSERT INTO lecturer (signature, name) VALUES ('0219', 'Kachniewska Magdalena')
INSERT INTO lecturer (signature, name) VALUES ('0952', 'Biernat Elżbieta -')
INSERT INTO lecturer (signature, name) VALUES ('2845', 'Koskowski Michał')
INSERT INTO lecturer (signature, name) VALUES ('0651', 'Warowny Paweł')
INSERT INTO lecturer (signature, name) VALUES ('1571', 'Kinowska Hanna')
INSERT INTO lecturer (signature, name) VALUES ('1180', 'Wyrozębski Paweł')
INSERT INTO lecturer (signature, name) VALUES ('0616', 'Wachowiak Piotr')
INSERT INTO lecturer (signature, name) VALUES ('2797', 'Krzepicka Alicja Katarzyna ')
INSERT INTO lecturer (signature, name) VALUES ('0490', 'Rogowski Waldemar')
INSERT INTO lecturer (signature, name) VALUES ('1137', 'Ciesielska-Maciągowska Dorota')
INSERT INTO lecturer (signature, name) VALUES ('0171', 'Grzywacz Jacek')
INSERT INTO lecturer (signature, name) VALUES ('0458', 'Podedworna-Tarnowska Dorota')
INSERT INTO lecturer (signature, name) VALUES ('0231', 'Kasiewicz Stanisław')
INSERT INTO lecturer (signature, name) VALUES ('1380', 'Korczyński Adam')
INSERT INTO lecturer (signature, name) VALUES ('0527', 'Sopińska Agnieszka')
INSERT INTO lecturer (signature, name) VALUES ('0058', 'Borowski Krzysztof')
INSERT INTO lecturer (signature, name) VALUES ('0627', 'Wielgórska-Leszczyńska Joanna')
INSERT INTO lecturer (signature, name) VALUES ('1249', 'Staszkiewicz Piotr')
INSERT INTO lecturer (signature, name) VALUES ('1355', 'Konopka Dorota')
INSERT INTO lecturer (signature, name) VALUES ('1027', 'Serwa Dobromił')
INSERT INTO lecturer (signature, name) VALUES ('0290', 'Król Marcin')
INSERT INTO lecturer (signature, name) VALUES ('2843', 'Czainska Katarzyna')
INSERT INTO lecturer (signature, name) VALUES ('1226', 'Szelągowska Anna')
INSERT INTO lecturer (signature, name) VALUES ('1178', 'Dąbrowski Tomasz')
INSERT INTO lecturer (signature, name) VALUES ('1060', 'Danik Lidia')
INSERT INTO lecturer (signature, name) VALUES ('0347', 'Marciszewska Elżbieta')
INSERT INTO lecturer (signature, name) VALUES ('0440', 'Paprocki Wojciech')
INSERT INTO lecturer (signature, name) VALUES ('1268', 'Strzelecki Paweł')
INSERT INTO lecturer (signature, name) VALUES ('0491', 'Rokicka-Broniatowska Anna')
INSERT INTO lecturer (signature, name) VALUES ('0480', 'Pieriegud Jana')
INSERT INTO lecturer (signature, name) VALUES ('0348', 'Marczakowska-Proczka Joanna')
INSERT INTO lecturer (signature, name) VALUES ('0484', 'Ramsza Michał')
INSERT INTO lecturer (signature, name) VALUES ('0366', 'Michalski Tomasz')
INSERT INTO lecturer (signature, name) VALUES ('0526', 'Sokół Hanna')
INSERT INTO lecturer (signature, name) VALUES ('0463', 'Polak Przemysław')
INSERT INTO lecturer (signature, name) VALUES ('0126', 'Fierla Andrzej')
INSERT INTO lecturer (signature, name) VALUES ('0367', 'Mielus Piotr')
INSERT INTO lecturer (signature, name) VALUES ('0345', 'Marciniak Zenon')
INSERT INTO lecturer (signature, name) VALUES ('0502', 'Rostkowski Tomasz')
INSERT INTO lecturer (signature, name) VALUES ('0148', 'Gołębiowski Tomasz')
INSERT INTO lecturer (signature, name) VALUES ('0013', 'Baran Radosław')
INSERT INTO lecturer (signature, name) VALUES ('1030', 'Johann Maria')
INSERT INTO lecturer (signature, name) VALUES ('0639', 'Wódz Danuta')
INSERT INTO lecturer (signature, name) VALUES ('0118', 'Danilewicz Dariusz')
INSERT INTO lecturer (signature, name) VALUES ('1281', 'Karbowski Adam')
INSERT INTO lecturer (signature, name) VALUES ('0572', 'Sikora Tomasz')
INSERT INTO lecturer (signature, name) VALUES ('1021', 'Sobiecki Grzegorz')
INSERT INTO lecturer (signature, name) VALUES ('0074', 'Cygler Joanna')
INSERT INTO lecturer (signature, name) VALUES ('1006', 'Delong Łukasz')
INSERT INTO lecturer (signature, name) VALUES ('0027', 'Bijak Wojciech')
INSERT INTO lecturer (signature, name) VALUES ('1032', 'Kowalski Arkadiusz ')
INSERT INTO lecturer (signature, name) VALUES ('0437', 'Pakulska Teresa')
INSERT INTO lecturer (signature, name) VALUES ('0207', 'Jarosiński Mirosław')
INSERT INTO lecturer (signature, name) VALUES ('0349', 'Marczewski Krzysztof')
INSERT INTO lecturer (signature, name) VALUES ('0604', 'Tuzimek Rafał')
INSERT INTO lecturer (signature, name) VALUES ('0699', 'Radło Mariusz J.')
INSERT INTO lecturer (signature, name) VALUES ('2723', 'Melnarowicz Krzysztof')
INSERT INTO lecturer (signature, name) VALUES ('1580', 'Barłożewski Krystian')
INSERT INTO lecturer (signature, name) VALUES ('0022', 'Bieć Maria')
INSERT INTO lecturer (signature, name) VALUES ('0444', 'Perek-Białas Jolanta')
INSERT INTO lecturer (signature, name) VALUES ('0495', 'Rószkiewicz Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('0514', 'Sierak Jacek')
INSERT INTO lecturer (signature, name) VALUES ('0738', 'Surma Jerzy')
INSERT INTO lecturer (signature, name) VALUES ('0152', 'Goliński Michał')
INSERT INTO lecturer (signature, name) VALUES ('0975', 'Rubaszek Michał')
INSERT INTO lecturer (signature, name) VALUES ('0003', 'Alińska Agnieszka')
INSERT INTO lecturer (signature, name) VALUES ('0393', 'Matusewicz Michał')
INSERT INTO lecturer (signature, name) VALUES ('0287', 'Karwowski Mariusz')
INSERT INTO lecturer (signature, name) VALUES ('0579', 'Szlęzak-Matusewicz Joanna')
INSERT INTO lecturer (signature, name) VALUES ('1109', 'Jamroży Marcin')
INSERT INTO lecturer (signature, name) VALUES ('0170', 'Grzymała Zbigniew')
INSERT INTO lecturer (signature, name) VALUES ('0603', 'Trzcińska Barbara')
INSERT INTO lecturer (signature, name) VALUES ('0093', 'Liberadzki Marcin')
INSERT INTO lecturer (signature, name) VALUES ('0299', 'Kluza Stanisław')
INSERT INTO lecturer (signature, name) VALUES ('0059', 'Boratyńska Agata')
INSERT INTO lecturer (signature, name) VALUES ('0411', 'Sobczak Andrzej')
INSERT INTO lecturer (signature, name) VALUES ('0633', 'Witek-Hajduk Marzanna')
INSERT INTO lecturer (signature, name) VALUES ('1138', 'Dec Paweł')
INSERT INTO lecturer (signature, name) VALUES ('0044', 'Bryx Marek')
INSERT INTO lecturer (signature, name) VALUES ('0995', 'Wiśniewski Piotr')
INSERT INTO lecturer (signature, name) VALUES ('1604', 'Szczurek Anna ')
INSERT INTO lecturer (signature, name) VALUES ('0190', 'Pindelski Mikołaj')
INSERT INTO lecturer (signature, name) VALUES ('1238', 'Kuszewski Piotr')
INSERT INTO lecturer (signature, name) VALUES ('1230', 'Sońta-Drączkowska Ewa')
INSERT INTO lecturer (signature, name) VALUES ('0399', 'Niedziółka Paweł')
INSERT INTO lecturer (signature, name) VALUES ('1206', 'Giedroyć Magdalena')
INSERT INTO lecturer (signature, name) VALUES ('1187', 'Lewandowski Michał')
INSERT INTO lecturer (signature, name) VALUES ('0294', 'Koleśnik Jan')
INSERT INTO lecturer (signature, name) VALUES ('1028', 'Kraj Kamil')
INSERT INTO lecturer (signature, name) VALUES ('0045', 'Brzoza-Brzezina Michał')
INSERT INTO lecturer (signature, name) VALUES ('0368', 'Mierzejewska Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('1572', 'Masłoń-Oracz Anna')
INSERT INTO lecturer (signature, name) VALUES ('1356', 'Pachocka Marta')
INSERT INTO lecturer (signature, name) VALUES ('0485', 'Rapacki Ryszard')
INSERT INTO lecturer (signature, name) VALUES ('0149', 'Kuźnar Andżelika')
INSERT INTO lecturer (signature, name) VALUES ('1232', 'Szyszka Adam')
INSERT INTO lecturer (signature, name) VALUES ('0355', 'Mazur Jolanta')
INSERT INTO lecturer (signature, name) VALUES ('0640', 'Wójcik Jacek')
INSERT INTO lecturer (signature, name) VALUES ('1496', 'Kurowski Wojciech')
INSERT INTO lecturer (signature, name) VALUES ('1016', 'Nowicka Katarzyna')
INSERT INTO lecturer (signature, name) VALUES ('1553', 'Maicki Piotr')
INSERT INTO lecturer (signature, name) VALUES ('0229', 'Karmańska Anna')
INSERT INTO lecturer (signature, name) VALUES ('1495', 'Księżopolski Krzysztof')
INSERT INTO lecturer (signature, name) VALUES ('0122', 'Ekes Maria')
INSERT INTO lecturer (signature, name) VALUES ('0517', 'Skowronek-Mielczarek Anna')
INSERT INTO lecturer (signature, name) VALUES ('0461', 'Podolska-Meducka Aldona')
INSERT INTO lecturer (signature, name) VALUES ('0570', 'Szypulewska-Porczyńska Alina D.')
INSERT INTO lecturer (signature, name) VALUES ('2835', 'Zagrajek Paweł')
INSERT INTO lecturer (signature, name) VALUES ('0456', 'Płoszajski Piotr')
INSERT INTO lecturer (signature, name) VALUES ('0215', 'Jung Bohdan')
INSERT INTO lecturer (signature, name) VALUES ('0373', 'Miroński Jacek')
INSERT INTO lecturer (signature, name) VALUES ('1025', 'Bentkowska Katarzyna')
INSERT INTO lecturer (signature, name) VALUES ('0048', 'Budzyński Wojciech')
INSERT INTO lecturer (signature, name) VALUES ('1279', 'Abramek Edyta')
INSERT INTO lecturer (signature, name) VALUES ('0709', 'Kasprzak Rafał')
INSERT INTO lecturer (signature, name) VALUES ('0068', 'Chmielecka Ewa')
INSERT INTO lecturer (signature, name) VALUES ('0362', 'Skrzypek Jerzy')
INSERT INTO lecturer (signature, name) VALUES ('0363', 'Abramowicz Witold')
INSERT INTO lecturer (signature, name) VALUES ('0082', 'Czarzasty Jan')
INSERT INTO lecturer (signature, name) VALUES ('0198', 'Jabłonowska Lidia')
INSERT INTO lecturer (signature, name) VALUES ('0674', 'Ziółkowska Marta')
INSERT INTO lecturer (signature, name) VALUES ('0217', 'Janowska Anna A.')
INSERT INTO lecturer (signature, name) VALUES ('5311', 'Gawryluk Michał')
INSERT INTO lecturer (signature, name) VALUES ('0562', 'Sznajder Andrzej')
INSERT INTO lecturer (signature, name) VALUES ('0263', 'Kowalczyk Barbara')
INSERT INTO lecturer (signature, name) VALUES ('0391', 'Mrówka Rafał')
INSERT INTO lecturer (signature, name) VALUES ('0392', 'Mirońska Dominika')
INSERT INTO lecturer (signature, name) VALUES ('1155', 'Żukowska Joanna')
INSERT INTO lecturer (signature, name) VALUES ('0801', 'Cicharska Magdalena')
INSERT INTO lecturer (signature, name) VALUES ('0504', 'Russel Piotr')
INSERT INTO lecturer (signature, name) VALUES ('0994', 'Kreczmańska-Gigol Katarzyna')
INSERT INTO lecturer (signature, name) VALUES ('0506', 'Rubach Paweł')
INSERT INTO lecturer (signature, name) VALUES ('0655', 'Wójcik Cezary')
INSERT INTO lecturer (signature, name) VALUES ('0182', 'Zajaczkowski Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('0327', 'Laszuk Marek')
INSERT INTO lecturer (signature, name) VALUES ('2746', 'Lipski Mariusz')
INSERT INTO lecturer (signature, name) VALUES ('1185', 'Wieczorek Maria')
INSERT INTO lecturer (signature, name) VALUES ('1272', 'Pawłowska Małgorzata')
INSERT INTO lecturer (signature, name) VALUES ('1154', 'Horodecka Anna')
INSERT INTO lecturer (signature, name) VALUES ('0408', 'Nowotniak-Poręba Justyna')
INSERT INTO lecturer (signature, name) VALUES ('0375', 'Modrzejewska-Leśniewska Joanna')
INSERT INTO lecturer (signature, name) VALUES ('0319', 'Lisowska Ewa')
INSERT INTO lecturer (signature, name) VALUES ('1507', 'Hoszman Adam')
INSERT INTO lecturer (signature, name) VALUES ('1516', 'Martysz Czesław')
INSERT INTO lecturer (signature, name) VALUES ('0280', 'Kurczewska Urszula')
INSERT INTO lecturer (signature, name) VALUES ('1251', 'Dryło Robert')
INSERT INTO lecturer (signature, name) VALUES ('0382', 'Morawski Wojciech')
INSERT INTO lecturer (signature, name) VALUES ('0065', 'Cenkier Agnieszka')
INSERT INTO lecturer (signature, name) VALUES ('1263', 'Łazor Jerzy')
INSERT INTO lecturer (signature, name) VALUES ('0553', 'Szapiro Tomasz')
INSERT INTO lecturer (signature, name) VALUES ('1326', 'Skrok Łukasz')
INSERT INTO lecturer (signature, name) VALUES ('1349', 'Mccaleb Agnieszka')

INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('110620', '0566', 'CLASSES', 'FRIDAY', '13:30:00', '15:10:00', 'W-62')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('120110', '0395', 'LECTURE', 'MONDAY', '11:40:00', '13:20:00', 'C-4b')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('120110', '1503', 'LECTURE', 'WEDNESDAY', '19:00:00', '20:40:00', 'C-2c')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('120151', '0273', 'LECTURE', 'FRIDAY', '17:10:00', '18:50:00', 'C-2a')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('120480', '0389', 'LECTURE', 'FRIDAY', '11:40:00', '13:20:00', 'G-324')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('120490', '1227', 'LECTURE', 'MONDAY', '15:20:00', '17:00:00', 'G-232')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('120700', '1066', 'LECTURE', 'TUESDAY', '17:10:00', '18:50:00', 'C-1b')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('120700', '1066', 'CLASSES', 'TUESDAY', '19:00:00', '20:40:00', 'C-2a')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('120920', '0014', 'LECTURE', 'TUESDAY', '13:30:00', '15:10:00', 'G-231')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('120920', '0662', 'LECTURE', 'FRIDAY', '11:40:00', '13:20:00', 'G-236')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('120920', '0662', 'CLASSES', 'FRIDAY', '13:30:00', '15:10:00', 'G-236')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('120921', '0301', 'LECTURE', 'TUESDAY', '13:30:00', '15:10:00', 'A-210')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('121040', '0350', 'LECTURE', 'MONDAY', '08:00:00', '09:40:00', 'G-012 (parter)')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('121040', '0442', 'LECTURE', 'FRIDAY', '13:30:00', '15:10:00', 'G-322')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('121110', '0470', 'LECTURE', 'TUESDAY', '13:30:00', '15:10:00', 'G-114')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('121390', '1066', 'LECTURE', 'THURSDAY', '17:10:00', '18:50:00', 'C-3b')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('121401', '0325', 'LECTURE', 'THURSDAY', '09:50:00', '11:30:00', 'Aula B')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('121500', '0991', 'LECTURE', 'WEDNESDAY', '15:20:00', '17:00:00', 'C-1b')
INSERT INTO course (subject_signature, lecturer_signature, type, day, start_time, end_time, venue) VALUES ('121500', '1888', 'LECTURE', 'THURSDAY', '13:30:00', '15:10:00', 'C-4a')


INSERT INTO field (name) VALUES ('Analiza danych - Big Data')
INSERT INTO field (name) VALUES ('E-biznes')
INSERT INTO field (name) VALUES ('Ekonomia')
INSERT INTO field (name) VALUES ('Finanse i rachunkowość')
INSERT INTO field (name) VALUES ('Metody ilościowe w ekonomii i systemy informacyjne')
INSERT INTO field (name) VALUES ('Międzynarodowe stosunki gospodarcze')
INSERT INTO field (name) VALUES ('Zarządzanie')


INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '223470', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '223090', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '223060', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '224390', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '223120', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '222080', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '222110', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '223050', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '222800', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '223110', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '223100', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '223480', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '223490', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '226160', true)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '220340', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '220570', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '220580', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '220620', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '222000', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '222050', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '222060', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '222580', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '222950', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '222990', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '230200', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '230240', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '231220', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '231450', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '233070', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '233180', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '233850', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '234060', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '234900', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '235410', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '236430', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '238310', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (1, '239200', false)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '222090', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '222260', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '222610', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '222620', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '222810', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '223250', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '223260', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '223270', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '223280', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '223290', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '223300', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '223350', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '223370', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '223390', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '223960', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '224380', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '226150', true)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '120110', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '220620', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '222160', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '222230', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '223310', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '230510', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '230770', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '230880', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '231220', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '231430', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '233070', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '233160', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '233880', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '234110', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '235250', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '235260', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '235280', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '235300', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '235310', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '235330', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '235340', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '235350', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '235360', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '235370', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '237990', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '238380', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '239200', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (2, '239951', false)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '221480', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222050', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222070', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222080', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222100', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222110', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222120', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222130', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222150', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222290', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222321', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222370', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222410', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222990', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '223010', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '223031', true)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '220380', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '220590', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222060', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222380', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '222940', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '223010', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '223031', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '231560', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '231571', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '232000', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '233200', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '233461', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '233910', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '234881', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (3, '234900', false)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '222090', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '222250', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '220430', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '222040', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '222120', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '222130', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '222160', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '220380', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '222490', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '220750', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '222460', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '220530', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '220740', true)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '220680', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '220960', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '221330', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '230060', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '230080', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '230910', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '231150', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '231170', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '231230', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '232160', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '232580', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '232650', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '233060', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '233350', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '233370', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '233450', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '233490', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '233580', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '233590', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '233680', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '233710', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '233910', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '233970', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '233990', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '234040', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '234100', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '234140', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '234150', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '234480', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '234490', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '234630', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '234720', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '234910', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '234920', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '235440', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '235450', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '235460', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '235730', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '236850', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '236960', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '238070', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (4, '239230', false)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '220340', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '220570', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '220580', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '220590', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '220620', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '221480', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '222000', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '222060', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '222080', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '222110', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '222120', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '222230', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '222260', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '222580', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '222800', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '222940', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '222990', true)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '120110', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '220440', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '222950', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '223120', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '223450', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '223470', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '223480', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '223490', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '230200', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '230240', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '230720', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '230770', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '230880', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '231110', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '231220', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '231430', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '231450', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '232080', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '232650', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '233030', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '233040', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '233070', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '233160', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '233180', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '233310', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '233640', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '233850', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '233880', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '233890', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '234060', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '234110', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '234650', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '234750', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '234900', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '235410', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (5, '236860', false)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '120480', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '121110', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '221320', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '221330', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '221340', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '221370', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '222050', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '222080', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '222090', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '222100', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '222120', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '222140', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '222340', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '222380', true)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '222451', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '223370', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '231420', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '232121', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '232301', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '232461', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '232650', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '233010', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '233291', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '234080', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '234670', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '234791', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '235150', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (6, '239170', false)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '120920', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '220440', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '220500', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '220770', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '220820', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '221470', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '222080', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '222090', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '222110', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '222160', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '222600', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '222610', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '222620', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '222810', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '222970', true)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '222980', true)

INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '120490', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '121390', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '121401', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '221320', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '222470', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '223330', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '223370', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '223390', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '223420', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '223960', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '224380', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '224410', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '225540', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '230300', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '230460', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '230510', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '230540', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '230570', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '230710', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '230820', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '230880', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '231090', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '231210', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '231380', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '231430', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '232600', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '232770', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '233070', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '233510', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '233890', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '234000', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '234080', false)
INSERT INTO field_subject(field_id, subject_signature, required ) VALUES (7, '234301', false)

